In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [3]:
(2 * np.ones(20)) ** np.arange(1, 21) / np.arange(1, 21)

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [4]:
fmul = (0.1 * np.ones(6)) ** (3 * np.arange(0, 6))
smul = (0.2 * np.ones(6)) ** (4 * np.arange(0, 6))
np.sum(fmul * smul)

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [5]:
a = np.zeros((8, 8))

a[::2 , ::2] = 1
a[1::2 , 1::2] = 1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [6]:
x = np.random.random((5, 2))
print(x)
x = np.array([np.sqrt(x[:, 0] ** 2 + x[:, 1] ** 2), np.arctan2(x[:, 1], x[:, 0])]).T; x

[[0.60830759 0.37396281]
 [0.91937196 0.0337762 ]
 [0.89817448 0.18758542]
 [0.87432673 0.63138976]
 [0.14012443 0.94055255]]


array([[0.71406324, 0.55120137],
       [0.9199922 , 0.03672182],
       [0.91755419, 0.20589231],
       [1.07847126, 0.6254336 ],
       [0.95093321, 1.42290314]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [7]:
x = np.random.random((10, 10))

idx = np.unravel_index(np.argmax(x), x.shape); idx

(9, 7)

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [8]:
x = np.random.random((10, 2))
y = np.random.random((1, 2))

print(x)
print(y)

dist = np.sqrt((x[:, 0] - y[:, 0]) ** 2 + (x[:, 0] - y[:, 1]) ** 2)
x[np.argmin(dist), :]

[[0.41372591 0.58455272]
 [0.45145228 0.46657906]
 [0.82532261 0.07115601]
 [0.10165029 0.74976258]
 [0.74923265 0.02519152]
 [0.84183578 0.86324922]
 [0.38421081 0.53368426]
 [0.18438941 0.73243301]
 [0.81963122 0.79479836]
 [0.94868069 0.92253101]]
[[0.712076   0.28927791]]


array([0.45145228, 0.46657906])

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [9]:
x = 6 * np.random.random(10) - 3
first_mask = x < 0
second_mask = (0 <= x) & (x <= 2)
third_mask = x >= 2
x[first_mask] = x[first_mask] ** 2 + 2 * x[first_mask] + 6
x[second_mask] = x[second_mask] + 6
x[third_mask] = x[third_mask] ** 2 + 4 * x[third_mask] + 6
x

array([ 5.62677665,  5.5849697 ,  6.76598811,  7.17045298,  6.92612681,
        7.34394243,  8.99431655, 20.14033826, 18.01000046,  5.11470112])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [10]:
a = np.random.random((10, 10))

a = a.T - np.mean(a, axis=1).T
a = a.T

np.mean(a, axis=1)

array([ 1.11022302e-17,  4.44089210e-17, -2.22044605e-17,  2.22044605e-17,
       -6.66133815e-17,  8.88178420e-17,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  1.11022302e-17])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [11]:
x = np.random.normal(loc=5, scale=2., size=1000)

mean = x.sum() / x.size
variance = ((x - mean) ** 2).sum() / x.size
mean, variance

(4.908297443135001, 4.104122734452325)

**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [12]:
a = np.ones((5, 5)) * np.arange(5)
a += a.T
a %= 5
a

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 0.],
       [2., 3., 4., 0., 1.],
       [3., 4., 0., 1., 2.],
       [4., 0., 1., 2., 3.]])

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [22]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 0, 0, 4, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [23]:
def better_sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    partial = np.repeat(np.cumsum(x), c).reshape((len(x), c)).astype("float32")
    val = s * np.random.random(c)
    partial -= val.T
    partial[partial >= 0] = 0
    
    return np.argmax(partial, axis=0)

better_sample([50, 3, 1, 7, 20], 5)    

array([3, 4, 4, 0, 0])